package Funcionarios;

import ClasseConexao.conexao;
import Funcionarios.Funcionarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class FormFuncionarios extends javax.swing.JFrame {

   public conexao conn = new conexao();
   FuncionariosControle fcntl = new FuncionariosControle();
   
    public FormFuncionarios() {
        initComponents();
        lbCod.setVisible(false);
        jTextFCod.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbDataAdmissao = new javax.swing.JLabel();
        lbCargo = new javax.swing.JLabel();
        lbSalario = new javax.swing.JLabel();
        lbDepartamento = new javax.swing.JLabel();
        jTextFNome = new javax.swing.JTextField();
        jTextFCPF = new javax.swing.JTextField();
        jTextFEndereco = new javax.swing.JTextField();
        jTextFTelefone = new javax.swing.JTextField();
        jTextFEmail = new javax.swing.JTextField();
        jTextFDataAdmissao = new javax.swing.JTextField();
        jTextFCargo = new javax.swing.JTextField();
        jTextFSalario = new javax.swing.JTextField();
        jTextFDepartamento = new javax.swing.JTextField();
        jButtonMostrar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        lbCod = new javax.swing.JLabel();
        jTextFCod = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMDados = new javax.swing.JMenu();
        jMenuDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNome.setText("Nome Completo:");

        lbCPF.setText("CPF:");

        lbEndereco.setText("Endereço:");

        lbTelefone.setText("Telefone:");

        lbEmail.setText("Email:");

        lbDataAdmissao.setText("Data de Admissão:");

        lbCargo.setText("Cargo:");

        lbSalario.setText("Salário:");

        lbDepartamento.setText("Departamento:");

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        lbCod.setText("Codigo:");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSalario)
                    .addComponent(lbCargo)
                    .addComponent(lbDataAdmissao)
                    .addComponent(lbEmail)
                    .addComponent(lbTelefone)
                    .addComponent(lbEndereco)
                    .addComponent(lbCPF)
                    .addComponent(lbNome)
                    .addComponent(lbCod)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonMostrar)
                        .addComponent(lbDepartamento)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                            .addComponent(jTextFSalario)
                            .addComponent(jTextFCargo)
                            .addComponent(jTextFDataAdmissao)
                            .addComponent(jTextFEmail)
                            .addComponent(jTextFTelefone)
                            .addComponent(jTextFEndereco)
                            .addComponent(jTextFCPF)
                            .addComponent(jTextFNome)
                            .addComponent(jTextFCod))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnAtualizar)
                        .addGap(36, 36, 36)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonFechar)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCod)
                    .addComponent(jTextFCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(jTextFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPF)
                    .addComponent(jTextFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(jTextFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(jTextFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(jTextFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataAdmissao)
                    .addComponent(jTextFDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCargo)
                    .addComponent(jTextFCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSalario)
                    .addComponent(jTextFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDepartamento)
                    .addComponent(jTextFDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostrar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnGravar)
                    .addComponent(btnExcluir)
                    .addComponent(jButtonFechar))
                .addGap(22, 22, 22))
        );

        jMDados.setText("File");

        jMenuDados.setText("Dados");
        jMenuDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDadosActionPerformed(evt);
            }
        });
        jMDados.add(jMenuDados);

        jMenuBar1.add(jMDados);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
       Funcionarios f = this.MontarFuncionarios();
       JOptionPane.showMessageDialog(null, f.getNomeCompleto()+" "+f.getCPF()+" "+
               f.getEndereco()+" "+f.getTelefone()+" "+f.getEmail()+" "+
               f.getDataAdmissao()+" "+f.getCargo()+" "+f.getSalario()+" "+
               f.getDepartamento());
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Funcionarios f = this.MontarFuncionarios();
        if (f != null && !jTextFCod.getText().trim().isEmpty()) {
            f.setCod(Integer.parseInt(jTextFCod.getText()));
            fcntl.update(f);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + "corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
         Funcionarios f = this.MontarFuncionarios();
        if (f != null) {
        fcntl.insert(f);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + " corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       if(!jTextFCod.getText().trim().isEmpty()){
         int cod = Integer.parseInt(jTextFCod.getText());
         fcntl.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Informe novamente...");
        }    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jMenuDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDadosActionPerformed
         FuncionariosControle fc = new FuncionariosControle();
         fc.selectALL();
    }//GEN-LAST:event_jMenuDadosActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFuncionarios().setVisible(true);
            }
        });
    }

    public Funcionarios MontarFuncionarios(){
        
        Funcionarios f = new Funcionarios();
        f.setNomeCompleto(jTextFNome.getText());
        f.setCPF(jTextFCPF.getText());
        f.setEndereco(jTextFEndereco.getText());
        f.setTelefone(jTextFTelefone.getText());
        f.setEmail(jTextFEmail.getText());
        f.setDataAdmissao(jTextFDataAdmissao.getText());
        f.setCargo(jTextFCargo.getText());
        f.setSalario(jTextFSalario.getText());
        f.setDepartamento(jTextFDepartamento.getText());
        return f;
    }
    
    public void Limpar(){
        jTextFCod.setText("");
        jTextFNome.setText("");
        jTextFCPF.setText("");
        jTextFEndereco.setText("");
        jTextFTelefone.setText("");
        jTextFEmail.setText("");
        jTextFDataAdmissao.setText("");
        jTextFCargo.setText("");
        jTextFSalario.setText("");
        jTextFDepartamento.setText("");        
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JMenu jMDados;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFCPF;
    private javax.swing.JTextField jTextFCargo;
    private javax.swing.JTextField jTextFCod;
    private javax.swing.JTextField jTextFDataAdmissao;
    private javax.swing.JTextField jTextFDepartamento;
    private javax.swing.JTextField jTextFEmail;
    private javax.swing.JTextField jTextFEndereco;
    private javax.swing.JTextField jTextFNome;
    private javax.swing.JTextField jTextFSalario;
    private javax.swing.JTextField jTextFTelefone;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbDataAdmissao;
    private javax.swing.JLabel lbDepartamento;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSalario;
    private javax.swing.JLabel lbTelefone;
    // End of variables declaration//GEN-END:variables
}
