package Fornecedores;

import ClasseConexao.conexao;
import Fornecedores.Fornecedores;
import Fornecedores.FornecedoresControle;
import javax.swing.JOptionPane;


public class FormFornecedores extends javax.swing.JFrame {
     public conexao conn = new conexao();

    FornecedoresControle fctrl = new FornecedoresControle();
    
    public FormFornecedores() {
        initComponents();
        lbCod.setVisible(true);
        jTextFCod.setVisible(true);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNomeEmpresa = new javax.swing.JLabel();
        lbCNPJ = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbNomeContato = new javax.swing.JLabel();
        lbTpProdServ = new javax.swing.JLabel();
        lbCondicoesPag = new javax.swing.JLabel();
        lbPrazoEntrega = new javax.swing.JLabel();
        jTextFNomeEmpresa = new javax.swing.JTextField();
        jTextFCNPJ = new javax.swing.JTextField();
        jTextFEndereco = new javax.swing.JTextField();
        jTextFTelefone = new javax.swing.JTextField();
        jTextFEmail = new javax.swing.JTextField();
        jTextFNomeContato = new javax.swing.JTextField();
        jTextFTpProdServ = new javax.swing.JTextField();
        jTextFCondicoesPag = new javax.swing.JTextField();
        jTextFPrazoEntrega = new javax.swing.JTextField();
        jButtonMostrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lbCod = new javax.swing.JLabel();
        jTextFCod = new javax.swing.JTextField();
        btnAttualizar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRelatorio = new javax.swing.JMenu();
        jmiDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNomeEmpresa.setText("Nome da Empresa:");

        lbCNPJ.setText("CNPJ:");

        lbEndereco.setText("Endereço:");

        lbTelefone.setText("Telefone:");

        lbEmail.setText("Email:");

        lbNomeContato.setText("Nome do Contato:");

        lbTpProdServ.setText("Tipo de Produto/Serviço:");

        lbCondicoesPag.setText("Condições de Pagamento:");

        lbPrazoEntrega.setText("Prazo de Entrega:");

        jTextFNomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNomeEmpresaActionPerformed(evt);
            }
        });

        jTextFPrazoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFPrazoEntregaActionPerformed(evt);
            }
        });

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        lbCod.setText("Codigo:");

        btnAttualizar.setText("Atualizar");
        btnAttualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttualizarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCondicoesPag)
                            .addComponent(lbEndereco)
                            .addComponent(lbCNPJ)
                            .addComponent(lbNomeEmpresa)
                            .addComponent(lbCod)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbEmail)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbNomeContato)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbTpProdServ)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                    .addComponent(jTextFTpProdServ, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbPrazoEntrega)
                                            .addGap(125, 125, 125)
                                            .addComponent(jTextFPrazoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lbTelefone)
                                            .addGap(168, 168, 168)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFCod)
                                                .addComponent(jTextFNomeEmpresa)
                                                .addComponent(jTextFCNPJ)
                                                .addComponent(jTextFEndereco)
                                                .addComponent(jTextFTelefone)
                                                .addComponent(jTextFCondicoesPag, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnFechar))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAttualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGravar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCod)
                    .addComponent(jTextFCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeEmpresa)
                    .addComponent(jTextFNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCNPJ)
                    .addComponent(jTextFCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(jTextFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(jTextFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(jTextFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeContato)
                    .addComponent(jTextFNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTpProdServ)
                    .addComponent(jTextFTpProdServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCondicoesPag)
                    .addComponent(jTextFCondicoesPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrazoEntrega)
                    .addComponent(jTextFPrazoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostrar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAttualizar)
                    .addComponent(btnGravar)
                    .addComponent(btnFechar))
                .addGap(15, 15, 15))
        );

        jmRelatorio.setText("File");

        jmiDados.setText("Dados");
        jmiDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDadosActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiDados);

        jMenuBar1.add(jmRelatorio);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFNomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFNomeEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFNomeEmpresaActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        Fornecedores f = this.MontarFornecedores();
        JOptionPane.showMessageDialog(null,f.getCod()+ "\n " +f.getNomeEmp()+" \n"+f.getCNPJ()+"\n "+
                f.getEndereco()+"\n "+f.getTelefone()+"\n "+f.getEmail()+" "+
                f.getNomeContato()+"\n "+f.getTipoProdServ()+"\n "+f.getCondPag()+"\n "+
                f.getPrazoEnt());
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
          if(!jTextFCod.getText().trim().isEmpty()){
         int cod = Integer.parseInt(jTextFCod.getText());
         fctrl.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Informe novamente...");
        }
              
          
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jTextFPrazoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFPrazoEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFPrazoEntregaActionPerformed

    private void btnAttualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttualizarActionPerformed
        Fornecedores f = this.MontarFornecedores();
        if (f != null && !jTextFCod.getText().trim().isEmpty()) {
            f.setCod(Integer.parseInt(jTextFCod.getText()));
            FornecedoresControle fcntl = new FornecedoresControle();
            fcntl.update(f);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + "corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAttualizarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Fornecedores f = this.MontarFornecedores();
        if (f != null) {
         fctrl.insert(f);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + " corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void jmiDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDadosActionPerformed
        FornecedoresControle fc = new FornecedoresControle();
        fc.SelectAll();
    }//GEN-LAST:event_jmiDadosActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFornecedores().setVisible(true);
            }
        });
    }
    
    public Fornecedores MontarFornecedores(){
    Fornecedores f = new Fornecedores();
    f.setNomeEmp(jTextFNomeEmpresa.getText());
    f.setCNPJ(jTextFCNPJ.getText());
    f.setEndereco(jTextFEndereco.getText());
    f.setTelefone(jTextFTelefone.getText());
    f.setEmail(jTextFEmail.getText());
    f.setNomeContato(jTextFNomeContato.getText());
    f.setTipoProdServ(jTextFTpProdServ.getText());
    f.setCondPag(jTextFCondicoesPag.getText());
    f.setPrazoEnt(jTextFPrazoEntrega.getText());
    return f;
}
    
    public void Limpar(){
     jTextFCod.setText("");
     jTextFNomeEmpresa.setText("");
     jTextFCNPJ.setText("");
     jTextFEndereco.setText("");
     jTextFTelefone.setText("");
     jTextFEmail.setText("");
     jTextFNomeContato.setText("");
     jTextFTpProdServ.setText("");
     jTextFCondicoesPag.setText("");
     jTextFPrazoEntrega.setText("");
     
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFCNPJ;
    private javax.swing.JTextField jTextFCod;
    private javax.swing.JTextField jTextFCondicoesPag;
    private javax.swing.JTextField jTextFEmail;
    private javax.swing.JTextField jTextFEndereco;
    private javax.swing.JTextField jTextFNomeContato;
    private javax.swing.JTextField jTextFNomeEmpresa;
    private javax.swing.JTextField jTextFPrazoEntrega;
    private javax.swing.JTextField jTextFTelefone;
    private javax.swing.JTextField jTextFTpProdServ;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenuItem jmiDados;
    private javax.swing.JLabel lbCNPJ;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbCondicoesPag;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNomeContato;
    private javax.swing.JLabel lbNomeEmpresa;
    private javax.swing.JLabel lbPrazoEntrega;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTpProdServ;
    // End of variables declaration//GEN-END:variables
}