
package Alunos;

import Alunos.Alunos;
import javax.swing.JButton;
import javax.swing.JOptionPane;


public class FormAlunos extends javax.swing.JFrame {

     AlunosControle acntrl = new AlunosControle();
     
    public FormAlunos() {
        initComponents();
        lbCod.setVisible(false);
        jTextFCod.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFCod = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbDataNasc = new javax.swing.JLabel();
        lbSerieAno = new javax.swing.JLabel();
        lbNomeResp = new javax.swing.JLabel();
        lbEscolaOrigem = new javax.swing.JLabel();
        jTextFNome = new javax.swing.JTextField();
        jTextFCPF = new javax.swing.JTextField();
        jTextFEndereco = new javax.swing.JTextField();
        jTextFTelefone = new javax.swing.JTextField();
        jTextFEmail = new javax.swing.JTextField();
        jTextFDataNasc = new javax.swing.JTextField();
        jTextFSerieAno = new javax.swing.JTextField();
        jTextFNomeResp = new javax.swing.JTextField();
        jTextFEscolaOrigem = new javax.swing.JTextField();
        jButtonMostrar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        lbCod = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jTextFCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFCodActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        lbNome.setText("Nome Completo:");

        lbCPF.setText("CPF:");

        lbEndereco.setText("Endereço:");

        lbTelefone.setText("Telefone:");

        lbEmail.setText("Email:");

        lbDataNasc.setText("Data de Nascimento:");

        lbSerieAno.setText("Série/Ano:");

        lbNomeResp.setText("Nome do Responsável:");

        lbEscolaOrigem.setText("Escola de Origem:");

        jTextFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFNomeActionPerformed(evt);
            }
        });

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        lbCod.setText("Código:");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEscolaOrigem)
                                    .addComponent(lbNomeResp)
                                    .addComponent(lbSerieAno)
                                    .addComponent(lbDataNasc)
                                    .addComponent(lbEmail)
                                    .addComponent(lbTelefone)
                                    .addComponent(lbEndereco)
                                    .addComponent(lbCPF)
                                    .addComponent(lbNome))
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbCod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFNomeResp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jTextFSerieAno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFDataNasc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFEscolaOrigem))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonMostrar)
                        .addGap(51, 51, 51)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnGravar)
                        .addGap(45, 45, 45)
                        .addComponent(btnExcluir)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonFechar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbCod)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(jTextFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCPF)
                    .addComponent(jTextFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEndereco)
                    .addComponent(jTextFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(jTextFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(jTextFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataNasc)
                    .addComponent(jTextFDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSerieAno)
                    .addComponent(jTextFSerieAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeResp)
                    .addComponent(jTextFNomeResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEscolaOrigem)
                    .addComponent(jTextFEscolaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostrar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnGravar)
                    .addComponent(btnExcluir)
                    .addComponent(jButtonFechar))
                .addGap(29, 29, 29))
        );

        jMenu1.setText("File");

        jmiDados.setText("Dados");
        jmiDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDadosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiDados);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        Alunos a = this.MontarAlunos();
        JOptionPane.showMessageDialog(null, a.getNomeCompleto()+" "+a.getCPF()+
               " "+a.getEndereco()+" "+a.getTelefone()+" "+a.getEmail()+" "+
               a.getDataNasc()+" "+a.getSerieAno()+" "+a.getNomeResp()+" "+
                a.getEscOrigem());
                
       
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void formAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formAncestorMoved

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        Alunos a = this.MontarAlunos();
            if (a != null && !jTextFCod.getText().trim().isEmpty()) {
            a.setCod(Integer.parseInt(jTextFCod.getText()));
            acntrl.update(a);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + "corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Alunos a = this.MontarAlunos();
          if (a != null){
           acntrl.insert(a);
          }else {
               JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
 
          }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       if(!jTextFCod.getText().trim().isEmpty()){
         int cod = Integer.parseInt(jTextFCod.getText());
         acntrl.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Informe novamente...");
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jmiDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDadosActionPerformed
         AlunosControle ac = new AlunosControle();
         ac.selectALL();
    }//GEN-LAST:event_jmiDadosActionPerformed

    private void jTextFCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFCodActionPerformed

    private void jTextFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlunos().setVisible(true);
            }
        });
    }
    
   
    public Alunos MontarAlunos(){
        Alunos a = new Alunos();
        a.setNomeCompleto(jTextFNome.getText());
        a.setCPF(jTextFCPF.getText());
        a.setEndereco(jTextFEndereco.getText());
        a.setTelefone(jTextFTelefone.getText());
        a.setEmail(jTextFEmail.getText());
        a.setDataNasc(jTextFDataNasc.getText());
        a.setSerieAno(jTextFSerieAno.getText());
        a.setNomeResp(jTextFNomeResp.getText());
        a.setEscOrigem(jTextFEscolaOrigem.getText());
        return a;
    }    
    
    public void Limpar () {
       jTextFCod.setText("");
       jTextFNome.setText("");
       jTextFCPF.setText("");
       jTextFEndereco.setText("");
       jTextFTelefone.setText("");
       jTextFEmail.setText("");
       jTextFDataNasc.setText("");
       jTextFSerieAno.setText("");
       jTextFNomeResp.setText("");
       jTextFEscolaOrigem.setText("");
    }           
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFCPF;
    private javax.swing.JTextField jTextFCod;
    private javax.swing.JTextField jTextFDataNasc;
    private javax.swing.JTextField jTextFEmail;
    private javax.swing.JTextField jTextFEndereco;
    private javax.swing.JTextField jTextFEscolaOrigem;
    private javax.swing.JTextField jTextFNome;
    private javax.swing.JTextField jTextFNomeResp;
    private javax.swing.JTextField jTextFSerieAno;
    private javax.swing.JTextField jTextFTelefone;
    private javax.swing.JMenuItem jmiDados;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbDataNasc;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbEscolaOrigem;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeResp;
    private javax.swing.JLabel lbSerieAno;
    private javax.swing.JLabel lbTelefone;
    // End of variables declaration//GEN-END:variables
}
