package Livros;

import Livros.Livros;
import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class FormLivros extends javax.swing.JFrame {

     LivrosControle lcntl = new LivrosControle();
     
    public FormLivros() {
        initComponents();
        lbCod.setVisible(false);
        jTextFCod.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbAutor = new javax.swing.JLabel();
        lbISBN = new javax.swing.JLabel();
        lbEditora = new javax.swing.JLabel();
        lbAnoPublicação = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbNumPaginas = new javax.swing.JLabel();
        lbIdioma = new javax.swing.JLabel();
        lbLocBiblioteca = new javax.swing.JLabel();
        jTextFTitulo = new javax.swing.JTextField();
        jTextFAutor = new javax.swing.JTextField();
        jTextFISBN = new javax.swing.JTextField();
        jTextFEditora = new javax.swing.JTextField();
        jTextFAnoPublicacao = new javax.swing.JTextField();
        jTextFGenero = new javax.swing.JTextField();
        jTextFNumPaginas = new javax.swing.JTextField();
        jTextFIdioma = new javax.swing.JTextField();
        jTextFLocBiblioteca = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lbCod = new javax.swing.JLabel();
        jTextFCod = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmiDados = new javax.swing.JMenu();
        jMenuDados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setText("Título:");

        lbAutor.setText("Autor:");

        lbISBN.setText("ISBN:");

        lbEditora.setText("Editora:");

        lbAnoPublicação.setText("Ano de Publicação:");

        lbGenero.setText("Gênero:");

        lbNumPaginas.setText("Número de Páginas:");

        lbIdioma.setText("Idioma:");

        lbLocBiblioteca.setText("Localização na Biblioteca:");

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lbCod.setText("Código:");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMostrar)
                        .addGap(25, 25, 25)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGravar)
                        .addGap(28, 28, 28)
                        .addComponent(btnExcluir)
                        .addGap(28, 28, 28)
                        .addComponent(btnFechar)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLocBiblioteca)
                            .addComponent(lbIdioma)
                            .addComponent(lbNumPaginas)
                            .addComponent(lbGenero)
                            .addComponent(lbAnoPublicação)
                            .addComponent(lbEditora)
                            .addComponent(lbISBN)
                            .addComponent(lbAutor)
                            .addComponent(lbCod)
                            .addComponent(lbTitulo))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFISBN, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFAnoPublicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFGenero, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFNumPaginas, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFLocBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jTextFCod))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCod)
                    .addComponent(jTextFCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(jTextFTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutor)
                    .addComponent(jTextFAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbISBN)
                    .addComponent(jTextFISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEditora)
                    .addComponent(jTextFEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAnoPublicação)
                    .addComponent(jTextFAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenero)
                    .addComponent(jTextFGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumPaginas)
                    .addComponent(jTextFNumPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdioma)
                    .addComponent(jTextFIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocBiblioteca)
                    .addComponent(jTextFLocBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar)
                    .addComponent(btnFechar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnGravar)
                    .addComponent(btnExcluir))
                .addGap(28, 28, 28))
        );

        jmiDados.setText("File");

        jMenuDados.setText("Dados");
        jMenuDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDadosActionPerformed(evt);
            }
        });
        jmiDados.add(jMenuDados);

        jMenuBar1.add(jmiDados);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        Livros l = this.MontarLivros();
        JOptionPane.showMessageDialog(null, l.getTitulo()+" "+l.getAutor()+" "+
                l.getISBN()+" "+l.getEditora()+" "+l.getAnoPubli()+" "+l.getGenero()+
                " "+l.getNumPag()+" "+l.getIdioma()+" "+l.getLocBiblioteca());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       Livros l = this.MontarLivros();
        if (l != null && !jTextFCod.getText().trim().isEmpty()) {
            l.setCod(Integer.parseInt(jTextFCod.getText()));
            lcntl.update(l);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + "corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
         Livros l = this.MontarLivros();
        if (l != null) {
        lcntl.insert(l);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + " corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
         if(!jTextFCod.getText().trim().isEmpty()){
         int cod = Integer.parseInt(jTextFCod.getText());
         lcntl.delete(cod);
        }else{
            JOptionPane.showMessageDialog(null,"Informe novamente...");
        } 
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jMenuDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDadosActionPerformed
        LivrosControle lc = new LivrosControle();
         lc.selectALL();
    }//GEN-LAST:event_jMenuDadosActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
         this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLivros().setVisible(true);
            }
        });
    }

    public Livros MontarLivros(){
        
        Livros l = new Livros();
        l.setTitulo(jTextFTitulo.getText());
        l.setAutor(jTextFAutor.getText());
        l.setISBN(jTextFISBN.getText());
        l.setEditora(jTextFEditora.getText());
        l.setAnoPubli(jTextFAnoPublicacao.getText());
        l.setGenero(jTextFGenero.getText());
        l.setNumPag(jTextFNumPaginas.getText());
        l.setIdioma(jTextFIdioma.getText());
        l.setLocBiblioteca(jTextFLocBiblioteca.getText());
        return l;
    }
    
    public void Limpar(){
        jTextFCod.setText("");
        jTextFTitulo.setText("");
        jTextFAutor.setText("");
        jTextFISBN.setText("");
        jTextFEditora.setText("");
        jTextFAnoPublicacao.setText("");
        jTextFGenero.setText("");
        jTextFNumPaginas.setText("");
        jTextFIdioma.setText("");
        jTextFLocBiblioteca.setText("");
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFAnoPublicacao;
    private javax.swing.JTextField jTextFAutor;
    private javax.swing.JTextField jTextFCod;
    private javax.swing.JTextField jTextFEditora;
    private javax.swing.JTextField jTextFGenero;
    private javax.swing.JTextField jTextFISBN;
    private javax.swing.JTextField jTextFIdioma;
    private javax.swing.JTextField jTextFLocBiblioteca;
    private javax.swing.JTextField jTextFNumPaginas;
    private javax.swing.JTextField jTextFTitulo;
    private javax.swing.JMenu jmiDados;
    private javax.swing.JLabel lbAnoPublicação;
    private javax.swing.JLabel lbAutor;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbEditora;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbISBN;
    private javax.swing.JLabel lbIdioma;
    private javax.swing.JLabel lbLocBiblioteca;
    private javax.swing.JLabel lbNumPaginas;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
