/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Produtos;

import Produtos.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author Senac
 */
public class FormProdutos extends javax.swing.JFrame {

     ProdutosControle pctrl = new ProdutosControle();
     
    public FormProdutos() {
        initComponents();
        lbCod.setVisible(false);
        jTextFCod.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNomeProduto = new javax.swing.JLabel();
        lbCodigoProduto = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();
        lbQuantEstoque = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbDataValidade = new javax.swing.JLabel();
        lbFornecedor = new javax.swing.JLabel();
        lbLocEstoque = new javax.swing.JLabel();
        jTextFNomeProduto = new javax.swing.JTextField();
        jTextFCodigoProduto = new javax.swing.JTextField();
        jTextFDescricao = new javax.swing.JTextField();
        jTextFPreco = new javax.swing.JTextField();
        jTextFQuantEstoque = new javax.swing.JTextField();
        jTextFCategoria = new javax.swing.JTextField();
        jTextFDataValidade = new javax.swing.JTextField();
        jTextFFornecedor = new javax.swing.JTextField();
        jTextFLocEstoque = new javax.swing.JTextField();
        jButtonMostrar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        lbCod = new javax.swing.JLabel();
        jTextFCod = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmidados = new javax.swing.JMenu();
        jmenudados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNomeProduto.setText("Nome do Produto:");

        lbCodigoProduto.setText("Código do Produto:");

        lbDescricao.setText("Descrição:");

        lbPreco.setText("Preço:");

        lbQuantEstoque.setText("Quantidade em Estoque:");

        lbCategoria.setText("Categoria:");

        lbDataValidade.setText("Data de Validade:");

        lbFornecedor.setText("Fornecedor:");

        lbLocEstoque.setText("Localização no Estoque:");

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        lbCod.setText("Codigo:");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeProduto)
                            .addComponent(lbCodigoProduto)
                            .addComponent(lbDescricao)
                            .addComponent(lbPreco)
                            .addComponent(lbQuantEstoque)
                            .addComponent(lbCategoria)
                            .addComponent(lbDataValidade)
                            .addComponent(lbFornecedor)
                            .addComponent(lbLocEstoque)
                            .addComponent(lbCod))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFCodigoProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFPreco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFQuantEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFDataValidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFLocEstoque, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jTextFCod))
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonMostrar)
                        .addGap(34, 34, 34)
                        .addComponent(btnAtualizar)
                        .addGap(38, 38, 38)
                        .addComponent(btnGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonFechar)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCod)
                    .addComponent(jTextFCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeProduto)
                    .addComponent(jTextFNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigoProduto)
                    .addComponent(jTextFCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescricao)
                    .addComponent(jTextFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreco)
                    .addComponent(jTextFPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantEstoque)
                    .addComponent(jTextFQuantEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCategoria)
                    .addComponent(jTextFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDataValidade)
                    .addComponent(jTextFDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFornecedor)
                    .addComponent(jTextFFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocEstoque)
                    .addComponent(jTextFLocEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMostrar)
                    .addComponent(jButtonFechar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnGravar)
                    .addComponent(btnExcluir))
                .addGap(16, 16, 16))
        );

        jmidados.setText("File");

        jmenudados.setText("Dados");
        jmenudados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenudadosActionPerformed(evt);
            }
        });
        jmidados.add(jmenudados);

        jMenuBar1.add(jmidados);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        Produto p = this.MontarProduto();
        JOptionPane.showMessageDialog(null, p.getNomeProd()+" "+p.getCodProd()+
                " "+p.getDescricao()+" "+p.getPreco()+" "+p.getQuantEstoque()+
                " "+p.getQuantEstoque()+" "+p.getCategoria()+" "+p.getDataValidade()+
                " "+p.getFornecedor()+" "+p.getLocEstoque());
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
         Produto p = this.MontarProduto();
        if (p != null && !jTextFCod.getText().trim().isEmpty()) {
            p.setCod(Integer.parseInt(jTextFCod.getText()));
            ProdutosControle fcntl = new ProdutosControle();
            fcntl.update(p);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + "corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void jmenudadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenudadosActionPerformed
        ProdutosControle pc = new ProdutosControle();
        pc.selectALL();
    }//GEN-LAST:event_jmenudadosActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
         this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Produto p = this.MontarProduto();
        if (p != null) {
         pctrl.insert(p);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos +"
                    + " corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProdutos().setVisible(true);
            }
        });
    }
    
    public Produto MontarProduto(){
        Produto p = new Produto();
        p.setNomeProd(jTextFNomeProduto.getText());
        p.setCodProd(jTextFCodigoProduto.getText());
        p.setDescricao(jTextFDescricao.getText());
        p.setPreco(jTextFPreco.getText());
        p.setQuantEstoque(jTextFQuantEstoque.getText());
        p.setCategoria(jTextFCategoria.getText());
        p.setDataValidade(jTextFDataValidade.getText());
        p.setFornecedor(jTextFFornecedor.getText());
        p.setLocEstoque(jTextFLocEstoque.getText());
        return p;
    }
    
    public void Limpar() {
       jTextFCod.setText("");
       jTextFNomeProduto.setText("");
       jTextFCodigoProduto.setText("");
       jTextFDescricao.setText("");
       jTextFPreco.setText("");
       jTextFQuantEstoque.setText("");
       jTextFCategoria.setText("");
       jTextFDataValidade.setText("");
       jTextFFornecedor.setText("");
       jTextFLocEstoque.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFCategoria;
    private javax.swing.JTextField jTextFCod;
    private javax.swing.JTextField jTextFCodigoProduto;
    private javax.swing.JTextField jTextFDataValidade;
    private javax.swing.JTextField jTextFDescricao;
    private javax.swing.JTextField jTextFFornecedor;
    private javax.swing.JTextField jTextFLocEstoque;
    private javax.swing.JTextField jTextFNomeProduto;
    private javax.swing.JTextField jTextFPreco;
    private javax.swing.JTextField jTextFQuantEstoque;
    private javax.swing.JMenuItem jmenudados;
    private javax.swing.JMenu jmidados;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCod;
    private javax.swing.JLabel lbCodigoProduto;
    private javax.swing.JLabel lbDataValidade;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbFornecedor;
    private javax.swing.JLabel lbLocEstoque;
    private javax.swing.JLabel lbNomeProduto;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQuantEstoque;
    // End of variables declaration//GEN-END:variables
}
